export const types = {
  FETCH_SEATS_REQUEST: "FETCH_SEATS_REQUEST",
  FETCH_SEATS_SUCCESS: "FETCH_SEATS_SUCCESS",
  FETCH_SEATS_FAIL: "FETCH_SEATS_FAIL",
  TOGGLE_CHOSEN_SEATS: "TOGGLE_CHOSEN_SEATS",
  RESERVE_SEATS: "RESERVE_SEATS",
  RESET_STORE: "RESET_STORE",
};
